-- Generated by `task schema` — do not edit, never applied.
-- The schema a fresh database has after all migrations run.

CREATE TABLE goose_db_version (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		version_id INTEGER NOT NULL,
		is_applied INTEGER NOT NULL,
		tstamp TIMESTAMP DEFAULT (datetime('now'))
	);

CREATE TABLE "user" (
  id         TEXT    PRIMARY KEY,
  email      TEXT    NOT NULL UNIQUE,
  created_at TEXT    NOT NULL DEFAULT (datetime('now')),
  day_start  INTEGER NOT NULL DEFAULT 18,
  day_end    INTEGER NOT NULL DEFAULT 34
, jot TEXT NOT NULL DEFAULT '', jot_version INTEGER NOT NULL DEFAULT 0);

CREATE TABLE session (
  token      TEXT    PRIMARY KEY,
  user_id    TEXT    NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  expires_at TEXT    NOT NULL,
  created_at TEXT    NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX session_user_id_idx ON session (user_id);

CREATE TABLE suppression (
    email      TEXT PRIMARY KEY,
    reason     TEXT NOT NULL CHECK (reason IN ('bounce', 'complaint')),
    detail     TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL
);

CREATE TABLE "login_code" (
  email      TEXT    PRIMARY KEY,
  user_id    TEXT    REFERENCES "user"(id) ON DELETE CASCADE,
  code_hash  TEXT    NOT NULL,
  attempts   INTEGER NOT NULL DEFAULT 0,
  expires_at TEXT    NOT NULL,
  created_at TEXT    NOT NULL DEFAULT (datetime('now'))
, attempts_since TEXT NOT NULL DEFAULT '');

CREATE INDEX login_code_user_id_idx ON login_code (user_id);

CREATE TABLE "block" (
  id         TEXT    PRIMARY KEY,
  label      TEXT    NOT NULL,
  position   INTEGER NOT NULL,
  span       INTEGER NOT NULL DEFAULT 1 CHECK (span >= 1),
  created_at TEXT    NOT NULL DEFAULT (datetime('now')),
  owner_id   TEXT    REFERENCES "user"(id) ON DELETE CASCADE,
  type       TEXT    NOT NULL DEFAULT 'shallow'
                     CHECK (type IN ('deep', 'shallow', 'break', 'appointment'))
);

CREATE TABLE jot_base (
    owner TEXT PRIMARY KEY REFERENCES "user" (id) ON DELETE CASCADE,
    version INTEGER NOT NULL,
    text TEXT NOT NULL
);

