// Command dumpschema migrates a throwaway SQLite file and prints its schema.
// It backs `task schema`, which writes internal/migrate/schema.sql — a
// reference artifact that is never applied to any database.
package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/GVPproj/unbusy.day/internal/migrate"
	_ "modernc.org/sqlite"
)

func main() {
	if err := run(context.Background()); err != nil {
		log.Fatalf("dumpschema: %v", err)
	}
}

func run(ctx context.Context) error {
	dir, err := os.MkdirTemp("", "unbusy-schema-*")
	if err != nil {
		return err
	}
	defer func() { _ = os.RemoveAll(dir) }()

	dsn := "file:" + filepath.Join(dir, "schema.db")
	if err := migrate.Run(ctx, dsn); err != nil {
		return err
	}

	db, err := sql.Open("sqlite", dsn)
	if err != nil {
		return err
	}
	defer func() { _ = db.Close() }()

	// Natural sqlite_master order = creation order, which mirrors the
	// migration sequence, so the dump is deterministic and reads in order.
	rows, err := db.QueryContext(ctx,
		`SELECT sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE 'sqlite_%'`)
	if err != nil {
		return err
	}
	defer rows.Close()

	fmt.Println("-- Generated by `task schema` — do not edit, never applied.")
	fmt.Println("-- The schema a fresh database has after all migrations run.")
	fmt.Println()
	for rows.Next() {
		var ddl string
		if err := rows.Scan(&ddl); err != nil {
			return err
		}
		fmt.Printf("%s;\n\n", ddl)
	}
	return rows.Err()
}
